name: "Genshin Impact Helper"

# Controls when the workflow will run
on:
  # push时触发一次
  workflow_dispatch:
  push:
  
  # 定时执行
  schedule:
  # 每天9点执行 时间格式 minute hour day month week 设置的时间是UTC 不是北京时间 需要+8
    - cron: "0 1 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install packages 
        run: npm install --production
        
      - name: Run sign
        env:
          COOKIE: ${{secrets.COOKIE}}
          MAIL_HOST: ${{secrets.MAIL_HOST}}
          MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
          MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
          MAIL_USERNAME_TO: ${{secrets.MAIL_USERNAME_TO}}
        run: npm start
